# Generated by Django 5.1.4 on 2025-01-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsignup',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist'), ('Nurse', 'Nurse'), ('Admin', 'Admin')], default='Patient', max_length=50),
        ),
    ]
