# Generated by Django 5.1.4 on 2025-01-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loginsignup_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsignup',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
