# Generated by Django 5.1.4 on 2025-01-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginsignup_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginsignup',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='Firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='LastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='MobileNumber',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='UserName',
            new_name='username',
        ),
    ]
