# Generated by Django 5.1.4 on 2025-01-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_loginsignup_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginsignup',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='first_name',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='mobile_number',
            new_name='MobileNumber',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='loginsignup',
            old_name='username',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='loginsignup',
            name='role',
        ),
    ]
