# Generated by Django 5.1.4 on 2025-01-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymAppointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.loginsignup')),
            ],
            options={
                'db_table': 'Gym_Appointments',
            },
        ),
    ]
