# Generated by Django 5.1.4 on 2025-01-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentID',
            new_name='appointment_id',
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='appointment_data',
        ),
    ]
